import '../app/[locale]/globals.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en"> {/* Default language at root */}
      <body>{children}</body>
    </html>
  );
}
